FROM python:3.13.0

RUN curl -LsSf https://astral.sh/uv/install.sh | sh 
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

ENV PYTHONPATH="/app/src"

COPY .python-version pyproject.toml uv.lock ./
COPY src/ ./src/

RUN uv sync --frozen --no-dev

CMD ["uv", "run", "python", "src/collector/main.py"]
